# Generated by Django 2.1.4 on 2018-12-28 03:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类')),
            ],
            options={
                'verbose_name': '分类管理',
                'verbose_name_plural': '分类管理',
            },
        ),
        migrations.CreateModel(
            name='keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='关键字')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pingtai.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PTArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('con', ckeditor.fields.RichTextField(max_length=20000, verbose_name='文章内容')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False, verbose_name='发布状态')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pingtai.Category', verbose_name='分类')),
                ('k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pingtai.keyword', verbose_name='关键字')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20, verbose_name='公司')),
                ('position', models.CharField(max_length=20, verbose_name='职位')),
                ('honny', models.CharField(max_length=20, verbose_name='爱好')),
                ('reason', models.TextField(max_length=200, verbose_name='申请理由')),
                ('realname', models.CharField(max_length=10, verbose_name='真实姓名')),
                ('sh', models.IntegerField(choices=[(0, '未审核'), (1, '审核中'), (2, '审核通过')], default=0)),
                ('u', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userauth.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '开通管理',
                'verbose_name_plural': '开通管理',
            },
        ),
    ]
