# Generated by Django 2.1.4 on 2018-12-28 03:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pingtai', '0001_initial'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('con', ckeditor.fields.RichTextField(max_length=30000, verbose_name='文章内容')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False, verbose_name='发布状态')),
                ('look', models.IntegerField(default=0)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.User', verbose_name='作者')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pingtai.Category', verbose_name='分类')),
                ('k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pingtai.keyword', verbose_name='关键字')),
            ],
        ),
    ]
