# Generated by Django 2.1.4 on 2018-12-28 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='手机号不符合规范', regex='^137|182|183|155')])),
                ('img', models.ImageField(upload_to='uploads/userimg')),
                ('c', models.IntegerField(choices=[(0, '普通用户'), (1, '高级用户')], default=0)),
            ],
            options={
                'verbose_name': '博客管理',
                'verbose_name_plural': '博客用户管理',
            },
        ),
    ]
